name = "discord-oidc"
main = "src/workers.ts"
compatibility_date = "2023-08-01"

kv_namespaces = [
  { binding = "KV", id = "fbf094f281004624b8cb173bc7a5a209", preview_id = "5abf0d59e2cd476d9d2b9945fe3e889e" }
]

[vars]
CLIENT_ID="1187247163768586280"
REDIRECT_URL="https://spacewak.cloudflareaccess.com/cdn-cgi/access/callback"
SERVERS_ROLE_CLAIMS=[
  "1088840877113352193"
]
